name: cypress
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install @badeball/cypress-cucumber-preprocessor
      run: npm install @badeball/cypress-cucumber-preprocessor --save-dev
    - name: Install multiple-cucumber-html-reporter
      run: npm i multiple-cucumber-html-reporter --save-dev
    - name: Run tests
      run: npm run cypress:execution
