name: Cypress test
on: [push]
jobs:
prepare-versions:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set-matrix
        name: Prepare
        run: echo "::set-output name=matrix::$(node -p "JSON.stringify(require('./package.json').peerDependencies['cypress'].split(' || '))")"
      - run: npm -v
test:
    needs: prepare-versions
    runs-on: ubuntu-20.04
    container:
      image: cypress/base:17.3.0
    strategy:
      matrix:
        cypress-version: ${{fromJson(needs.prepare-versions.outputs.matrix)}}
        
 steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm@${{ matrix.cypress-version }}
      - name: Cache Cypress binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress@${{ matrix.cypress-version }}
      - name: Install dependencies
        run: npm install
      - name: Install @badeball/cypress-cucumber-preprocessor
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Install @bahmutov/cypress-esbuild-preprocessor esbuild
        run: npm i -D cypress @bahmutov/cypress-esbuild-preprocessor esbuild
      - name: Change owner
        run: "chown root: ."
      - name: Deps  
        env:
          CYPRESS_INSTALL_BINARY: "0"
          CUCUMBER_JSON_FORMATTER_URL: https://github.com/cucumber/common/releases/download/json-formatter%2Fgo%2Fv19.0.0/cucumber-json-formatter-windows-amd64
        run: |
           npm install --force && \
           npm install --no-save cypress@${{ matrix.cypress-version }} && \
           env -u CYPRESS_INSTALL_BINARY npx cypress install && \
           curl -L $CUCUMBER_JSON_FORMATTER_URL > /usr/bin/cucumber-json-formatter && \
           chmod +x /usr/bin/cucumber-json-formatter
      - name: Build
        run: npm run build
      - name: Cypress run
        run: npm run cypress:execution
