name: Cypress test
on: [push]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install @badeball/cypress-cucumber-preprocessor
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Install @bahmutov/cypress-esbuild-preprocessor esbuild
        run: npm i -D cypress @bahmutov/cypress-esbuild-preprocessor esbuild
      - name: Cypress run
        run: npm run cypress:execution
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            config-file: cypress.config.js
            browser: chrome
