name: Cypress test
on: [push]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Cache Cypress binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress@${{ matrix.cypress-version }}
      - name: Install dependencies
        run: npm install
      - name: Install @badeball/cypress-cucumber-preprocessor
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Install @bahmutov/cypress-esbuild-preprocessor esbuild
        run: npm i -D cypress @bahmutov/cypress-esbuild-preprocessor esbuild
      - name: Deps  
        env:
          CYPRESS_INSTALL_BINARY: "0"
          CUCUMBER_JSON_FORMATTER_URL: https://github.com/cucumber/common/releases/download/json-formatter%2Fgo%2Fv19.0.0/cucumber-json-formatter-windows-amd64
          run: |
           npm install --force && \
           npm install --no-save cypress@${{ matrix.cypress-version }} && \
           env -u CYPRESS_INSTALL_BINARY npx cypress install && \
           curl -L $CUCUMBER_JSON_FORMATTER_URL > /usr/bin/cucumber-json-formatter && \
           chmod +x /usr/bin/cucumber-json-formatter
      - name: Build
        run: npm run build
      - name: Cypress run
        uses: npm run cypress:execution/github-action@v2
        with:
            config-file: cypress.config.js
            browser: chrome
